version: '3.8'

name: jenkins-windows
services:
  jenkins:
    build: .
    container_name: controller
    privileged: true
    user: root
    ports:
      - "9090:8080"
      - "50000:50000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./jenkins_home:/var/jenkins_home
      

