version: '3.8'

networks:
  docker:

name: jenkins-passbolt

services:

  jenkins:
    container_name: jenkins-controller
    image: jenkins/jenkins:latest-jdk17
    build: .
    depends_on:
      - dind 
    user: root
    restart: always
    networks:
      - docker
    ports:
      - ${JENKINS_EXPOSE_PORT}:8080
      - 50000:50000
    tty: true
    privileged: true
    volumes:
      - jenkins_data_volume:/var/jenkins_home
      - jenkins_certs_volume:/certs/client:ro
      - jenkins_home_volume:/home
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1

  dind:
    container_name: jenkins-dind
    image: docker:dind
    privileged: true
    restart: always
    networks:
      docker:
        aliases:
          - docker
    ports:
      - 2376:2376
    volumes:
      - jenkins_data_volume:/var/jenkins_home
      - jenkins_certs_volume:/certs/client
      - jenkins_home_volume:/home
    environment:
      - DOCKER_TLS_CERTDIR=/certs
      - DOCKER_DRIVER=overlay2
  
  db:
    container_name: passbolt-database
    image: mariadb:11.5.2
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
      MYSQL_DATABASE: "passbolt"
      MYSQL_USER: "passbolt"
      MYSQL_PASSWORD: "P4ssb0lt"
    volumes:
      - passbolt_database_volume:/var/lib/mysql
    networks:
      - docker
  
  passbolt:
    container_name: passbolt-app
    image: passbolt/passbolt:latest-ce
    restart: unless-stopped
    depends_on:
      - db
    environment:
      APP_FULL_BASE_URL: ${APP_FULL_BASE_URL}
      DATASOURCES_DEFAULT_HOST: "db"
      DATASOURCES_DEFAULT_USERNAME: "passbolt"
      DATASOURCES_DEFAULT_PASSWORD: "P4ssb0lt"
      DATASOURCES_DEFAULT_DATABASE: "passbolt"
      EMAIL_TRANSPORT_DEFAULT_HOST: ${EMAIL_TRANSPORT_DEFAULT_HOST}
      EMAIL_TRANSPORT_DEFAULT_PORT: ${EMAIL_TRANSPORT_DEFAULT_PORT}
      EMAIL_TRANSPORT_DEFAULT_USERNAME: ${EMAIL_TRANSPORT_DEFAULT_USERNAME}
      EMAIL_TRANSPORT_DEFAULT_PASSWORD: ${EMAIL_TRANSPORT_DEFAULT_PASSWORD}
    volumes:
      - passbolt_gpg_volume:/etc/passbolt/gpg
      - passbolt_jwt_volume:/etc/passbolt/jwt
    command:
      [
        "/usr/bin/wait-for.sh",
        "-t",
        "0",
        "db:3306",
        "--",
        "/docker-entrypoint.sh",
      ]
    ports:
      - ${PASSBOLT_EXPOSE_PORT}:80
      - ${PASSBOLT_HTTPS_EXPOSE_PORT}:443
    networks:
      - docker

volumes:
  passbolt_database_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOST_PASSBOLT_DATABASE_PATH}
  passbolt_gpg_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOST_PASSBOLT_GPG_PATH}

  passbolt_jwt_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOST_PASSBOLT_JWT_PATH}

  jenkins_data_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOST_JENKINS_DATA_PATH}

  jenkins_certs_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOST_JENKINS_CERTS_PATH}

  jenkins_home_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOST_JENKINS_HOME_PATH}

      

