version: '3.8'

networks:
  docker:

name: jenkins

services:

  jenkins:
    container_name: jenkins-controller
    image: jenkins/jenkins:latest-jdk17
    restart: always
    networks:
      - docker
    ports:
      - 8888:8080
      - 50000:50000
    tty: true
    volumes:
      - /home/lbriza/_service-data/jenkins/data:/var/jenkins_home
      - /home/lbriza/_service-data/jenkins/certs:/certs/client:ro
      - /home/lbriza/_service-data/jenkins/home:/home
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1

  dind:
    container_name: jenkins-dind
    image: docker:dind
    privileged: true
    restart: always
    networks:
      docker:
        aliases: 
          - docker
    ports:
      - 2376:2376
    tty: true
    volumes:
      - /home/lbriza/_service-data/jenkins/data:/var/jenkins_home
      - /home/lbriza/_service-data/jenkins/certs:/certs/client
      - /home/lbriza/_service-data/jenkins/home:/home
    environment:
      - DOCKER_TLS_CERTDIR=/certs
      

